apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: default
spec:
  type: NodePort  # 便于从Docker Desktop外部访问
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 30317  # 指定NodePort端口
    - name: ui
      port: 16686
      targetPort: 16686
      nodePort: 30686  # 指定NodePort端口
    - name: otlp-http
      port: 4318
      targetPort: 4318
      nodePort: 30318  # 指定NodePort端口
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 16686
              name: ui
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: COLLECTOR_OTLP_HTTP_ENABLED
              value: "true"
            - name: LOG_LEVEL
              value: "info"
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 10
            periodSeconds: 30